### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by Ged2323** [fbsamples/ios-friend-smash#8]
Hi once you get the access token how do you access the scopes that are requested?

**Comment by shir0i84** [comment]
Hi there would it be possible to clarify which permissions are you interested in? There is a list of different permissions available here: https://developers.facebook.com/docs/facebook-login/permissions.

For example, regarding the permission user_friends (which is commonly requested), you can refer to the documentation here: https://developers.facebook.com/docs/graph-api/reference/user/friends

**Comment by Ged2323** [comment]
How would you get the user name and email?

**Comment by youminkim** [comment]
You can use Graph API _/me?fields=name,email_

Try it in Graph API Explorer:
https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=me%3Ffields%3Did%2Cname%2Cemail&version=v2.6

**Comment by youminkim** [comment]
Closing this issue but feel free to reopen.
